### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ajeetbunny** [Sneha2405/Online-Examination-System#1]
Can you please provide the database file

**Comment by sneha-tarnekar** [comment]
[OnlineExamination.zip](https://github.com/Sneha2405/Online-Examination-System/files/6183490/OnlineExamination.zip)
Here's the database file , just need to export in your database. If you have any more quires then you can ask undoubtedly.

**Comment by ajeetbunny** [comment]
Can you please send the whole project.

Thanks for the help

**Comment by ajeetbunny** [comment]
Thanks for the help , The project is working fine .

**Comment by sneha-tarnekar** [comment]
My pleasure
